### ISSUE TITLE
juicebox_assembly_converter.py off by one converting to agp

### ISSUE THREAD

**Issue by erondeau** [phasegenomics/juicebox_scripts#13] opened 2019-01-03 01:34 UTC
Hello,

I'm curious about a change made recently to the the .assembly test data included in the "./tests/collateral/"  directory. I see the comment for the commit "Correct incorrect .assembly file test data, which had an off-by-one error in contig lengths (should have been length+1)". I'm curious why they should be length +1? The ".assembly" I've exported from Juicebox (v1.8.8) has the contig length in the third column, not contig length +1 as shown in the new test data. 

Thanks for your help, very useful scripts.

Eric

P.S. I ask because using a Juicebox .assembly and my fasta with the current converter script, the lengths of the contigs/scaffolds are all 1bp too small in the subsequent agp file

**Comment by shawnpg** [comment] 2019-01-03 18:20
Hi Eric,

Glad you are finding the scripts useful!

Those changes were introduced because someone was attempting to submit an assembly generated with them to NCBI, and they were getting errors from the system that the .AGP file and the .FASTA file were not consistent with each other. The changes to the test cases were made based on our understanding of how to correct those errors; however, the .assembly file format is unspecified, and there are some ambiguities in what is supposed to happen here. We've gone around several times on it.

What appeared to be the case was that the third column was an offset to the next contig (so length+1) rather than just the contig length. However it's entirely possible different versions of Juicebox represent the data slightly differently, or that we are still wrong about our interpretation of the data. Can you just share a snippet of your .assembly file and the corresponding contigs so we can have a look?

Thanks,

Shawn

**Comment by erondeau** [comment] 2019-01-03 22:09
Hello Shawn,

Certainly! I've taken out 4 short ones as an example. 
Fasta: 
[example.short.seqs.fasta.gz](https://github.com/phasegenomics/juicebox_scripts/files/2725394/example.short.seqs.fasta.gz)
 Assembly:
[example.short.seqs.assembly.gz](https://github.com/phasegenomics/juicebox_scripts/files/2725376/example.short.seqs.assembly.gz)

scaffold00901: 2,108bp
scaffold00902: 1,697bp
scaffold00903: 1,564bp
scaffold00904: 2,158bp


Using Commit 7692ad5 (pull request 6) produces the expected result:
[example.short.seqs.prior-commit.agp.gz](https://github.com/phasegenomics/juicebox_scripts/files/2725383/example.short.seqs.prior-commit.agp.gz)

>PGA_scaffold_1	1	2108	1	W	scaffold00901	1	2108	+
PGA_scaffold_2	1	1697	1	W	scaffold00902	1	1697	+
PGA_scaffold_3	1	1564	1	W	scaffold00903	1	1564	+
PGA_scaffold_4	1	2158	1	W	scaffold00904	1	2158	+

Using Commit 63c8df0 (current), each are 1bp short:
[example.short.seqs.current-commit.agp.gz](https://github.com/phasegenomics/juicebox_scripts/files/2725385/example.short.seqs.current-commit.agp.gz)

>PGA_scaffold_1__1_contigs__length_2107	1	2107	1	W	scaffold00901	1	2107	+
PGA_scaffold_2__1_contigs__length_1696	1	1696	1	W	scaffold00902	1	1696	+
PGA_scaffold_3__1_contigs__length_1563	1	1563	1	W	scaffold00903	1	1563	+
PGA_scaffold_4__1_contigs__length_2157	1	2157	1	W	scaffold00904	1	2157	+

I've also run the "generate-assembly-file-from-fasta" in the 3d-dna package (Software version: 180922) on the test data included with juicebox_scripts
` awk -f /path/to/3d-dna/utils/generate-assembly-file-from-fasta.awk test.fasta > test.assembly`
The resulting assembly file ([test.assembly.gz](https://github.com/phasegenomics/juicebox_scripts/files/2725403/test.assembly.gz)) looks like the prior juicebox_scripts commit.

Thanks for your help!

Eric

**Comment by neagef** [comment] 2021-04-23 13:06
Hello Shawn,
Me too, I've been trying to create a .agp file from an .assembly file in order to submit to the NCBI. My file was generated after manual curation of the assembly using Juicebox.
I also noted the difference in size between the size of each sequence shown by the .assembly file and the one in the resulting .agp, when I used a version cloned mars 8 (either commit cf7c0aa or 6264967).
I confirmed with two different methods that the size on the third column of the assembly file is the actual size of each sequence, while each sequence or fragment has a size of -1 in the .agp.
I downloaded commit 7692ad5 mentioned in this thread as giving the correct sizes, but it seems that the specifications of the assembly file had changed since, because it throws an error concerning certain debris contigs (KeyError: 'T001462:::debris' ).
Then I saw that there is a more recent commit (4d3d297), but with it, the script gives me the following error:
WARNING: trying to map debris fragment T000100:::debris to the whole original contig. This contig may have been trashed in Juicebox. Lengths of orig and debris are 105925, 105924.
Traceback (most recent call last):
  File "/homedir/bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 888, in <module>
    simple_chr_names=simple_chr_names)
  File "/homedirt/bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 91, in process
    sequences = self._add_breaks(sequences, assembly_map)
  File "/homedir/bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 292, in _add_breaks
    raise BadContigNameError("Mapping of debris to original contig failed- lengths are different!!")
__main__.BadContigNameError: Mapping of debris to original contig failed- lengths are different!!
 
Once again, the size of the sequence is 105925, not 105924. 
So, for the moment, I don't have a reliable .agp file to work with. 
Do you have an idea of what could be wrong here? 
Thank you.

**Comment by neagef** [comment] 2021-04-23 13:54
One precision concerning the fasta files obtained with commit t cf7c0aa or 6264967. (I wasn't able to get a .agp file with last commit)
Sizes of the contigs that are not fragmented seem to be treated correctly by the juicebox_assembly_converter.py script , but when they are fragmented (or marked as debris) their size is -1 of the real size. Examples from some chromosomes and some un-anchored contigs:

3D-DNA |  bp | juicebox_assembly_converter.py |  bp
-- | -- | -- | --
HiC_scaffold_14 | 130341200 | Chromosome14 | 130344896
HiC_scaffold_15 | 120043012 | Chromosome15 | 120042975
HiC_scaffold_16 | 71099779 | Chromosome16 | 71099876
HiC_scaffold_17 | 29403 | T140844 | 29403
HiC_scaffold_18 | 20248 | T021999 | 20248
HiC_scaffold_19 | 18120 | T022137___fragment_1 | 18119
HiC_scaffold_20 | 40584 | T076342 | 40584
HiC_scaffold_21 | 29061 | T003521___fragment_2 | 29060
HiC_scaffold_22 | 19406 | T075766 | 19406
HiC_scaffold_23 | 28137 | Chromosome23 | 28137
HiC_scaffold_31 | 5000 | T011998___fragment_2___debris | 4999
HiC_scaffold_32 | 5000 | T014405___fragment_2___debris | 4999
HiC_scaffold_33 | 2000 | T010136___fragment_2___debris | 1999

As a consequence, chromosomes' sizes  vary a lot.
Thank you

**Comment by shawnpg** [comment] 2021-05-04 07:28
Hi,

Thanks for reporting this issue! If only everyone could agree on one indexing scheme :) We believe we have fixes in the branch `fix_off_by_one_2`. Can you check that out and let us know if that resolves your issues?

Thanks,

Shawn

**Comment by neagef** [comment] 2021-05-04 07:48
Hi Shawn, Thank you for your answer. 
I tested several changes I made to commit 4d3d297, and only by getting rid of the  ' -1'  part at the end of line 287 I was able to run the script. 
The problem is that the final size for each chromosome, given by the agp file don't correspond to the sizes obtained on the fasta file, and they also differ from the FINAL.fasta file generated by 3D-DNA.
I was going to calculate the expected size for each chromosome  using the information from the assembly file to see who is wright.
I'll try the branch you suggest and come back to you.
Best
Andrea

**Comment by neagef** [comment] 2021-05-04 11:39
Hi Shawn, Thank you for your answer.
I tested several changes I made to commit 4d3d297, and only by getting rid of the ' -1'  at the end of line 287 I was able to run the script.
With this change, the resulting fasta file seem to have the correct sequence sizes. 
I calculated the expected size for each chromosome using the information from the assembly file. The file obtained with the modified 4d3d297 commit gets them right.
Your "fix_off_by_one_2" is still of by -1 per contig on the fasta obtained.
Also, the sizes for some (not all) of the chromosomes in the FINAL.fasta file generated by 3D-DNA are different from what it is expected.

As far as my data show, if you change line 287 from commit 4d3d297 to 
orig_len = len(sequences[nondebris_name])
the script will give you a fasta  file with the expected sequence sizes. However, I'm not sure about the agp's.

If I take for example sequence T000274, that I know  is 22939 bp long, and I check  our agp file before the HiC analysis I have this line:
T000274	1	22939	1	W	T000274	1	22939	+

The agp created with the modified 4d3d297 commit says :
Chromosome1	411513	434450	3	W	T000274	1	22938	-

and the one obtained with the "fix_off_by_one_2" branch:
Chromosome1	411513	434450	3	W	T000274	1	22938	-

With the .assembly file I get: 
grep "T000274" check.FINAL.order.assembly 
>T000274 10020 22939

So, shouldn't be the 8th column of the agp equivalent to the sequence size in the assembly and original fasta files (and so col3-col2 +1 = 22939 )?

Best
Andrea

PS: I just erased my previous message after manually checking the expected sequence sizes.

**Comment by shawnpg** [comment] 2021-05-07 06:14
Hi Andrea,

Great, thanks! Glad it's at least moving in the right direction. I did some investigating and think you are right about line 287, so we are changing it to that.

The lines you show for T000274 are interesting. The length in the 8th column of 22938 is actually already equal to col3 - col2 + 1, so I wonder if col3 is one too small or col2 is one too big. What do you see at the start of Chromosome1, the very first few lines? Does everything appear to be too short by one, or something else? It looks like the code is supposed to be doing the right thing based on our unit tests, but I wonder if we missed some cases.

Thanks,

Shawn

**Comment by neagef** [comment] 2021-05-07 13:03
Hi Shawn,
I think that neither col3 is one too small nor col2 is one too big, the problem comes from col8.

Yes, colum 8th is already col3 - col2 + 1, but that column should reflect (be equal to) the size of the sequence/fragment. 
The file specifications (https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/) says about col8 :
"If column 5 not equal to N or U: This column specifies the end of the part of the component that contributes to the object in column 1 (in component coordinates)."

I had a previous version of my assembly (submited and accepted by the NCBI), and in its corresponding agp file this column was equivalent to the contig size. This same size is also present in my .assembly file derived from Juicebox (third column on the contig list)

If I check the contig/fragment sizes from the beginning of Chromosome1:
T003900:::fragment_2 = 411413
T000274= 22939
T039572= 8431
T095563= 19888

And compare them to the new agp that I obtained :
Chromosome1	1	411412	1	W	T003900:::fragment_2	1	411412	+
Chromosome1	411413	411512	2	U	100	scaffold	yes	paired-ends
Chromosome1	411513	434450	3	W	T000274	1	22938	-
Chromosome1	434451	434550	4	U	100	scaffold	yes	paired-ends
Chromosome1	434551	442980	5	W	T039572	1	8430	+
Chromosome1	442981	443080	6	U	100	scaffold	yes	paired-ends
Chromosome1	443081	462967	7	W	T095563	1	19887	-

I see that the 8th column is off by -1 base, and that affects the start/end for every line thereafter. 

What I expect is:
Chromosome1     1       411413  1       W       T003900:::fragment_2    1       411413  +
Chromosome1     411414  411513  2       U       100     scaffold        yes     paired-ends
Chromosome1     411514  434452  3       W       T000274 1       22939   -
Chromosome1     434453  434552  4       U       100     scaffold        yes     paired-ends
Chromosome1     434553  442983  5       W       T039572 1       8431    +
Chromosome1     442984  443083  6       U       100     scaffold        yes     paired-ends
Chromosome1     443084  462971  7       W       T095563 1       19888   -

So right now, depending on the commit, I found: 

For commit  4d3d297 with the correction in line 287 gives:
- A fasta file with the correct sequence sizes
- A agp file with all lines off by -1 on the 8th column and in consequence, coordinates (start-end) in cols. 2 and 3  off by -1

For branch "fix_off_by_one_2"
- A fasta file with sizes -1 base for each contig
- A agp file with all lines off by -1 on the 8th column and in consequence, coordinates (start-end) in cols. 2 and 3  off by -1

So, to answer to your question, as far as my data shows, everything in the agp file appears to be too short by 1. Your code is indeed doing the right thing, but it takes the wrong information to start with.

I hope that this information helps.
Best
Andrea

**Comment by shawnpg** [comment] 2021-05-14 19:29
Hi Andrea,

Thank you very much. All those details were helpful. Based on looking at what you are seeing vs. what you are expecting, I believe based on them that the underlying issue was that column 3 was one too small. Column 8 is calculated in part from column 3, so the error in column 3 was also reflected there. Because the code represents the assembly in a common data structure, this same issue would have affected the FASTA file.

I've checked in a possible fix to fix_off_by_one_2. Can you pull the latest there and see if it resolves the problem for you?

Thanks,

Shawn

**Comment by neagef** [comment] 2021-05-17 08:55
Hi Shawn,
Thank you for the new script. I think that you nailed it!
I'm obtaining the expected output (agp and fasta sizes).
Best.
Andrea

**Comment by shawnpg** [comment] 2021-05-22 04:31
The fix has been reviewed and merged to master, and unit tests have been updated to prevent it from regressing. Thanks so much for all your help sorting it out @neagef !

Shawn

**Closed as completed** 2021-05-22 04:31 UTC
